### ISSUE TITLE
IO_ERR for lua.org

### ISSUE THREAD

**Issue by bugabinga** [mattias-p/linky#14]
Hi!

Thanks for making ´linky´. I use it to lint my little website!

´linky´ returns an `IO_ERR` for https://www.lua.org/.
But the URL resolves fine in the browser.

__test.md__:

```md
[SUCCESS](https://bugabinga.net)
[FAIL](https://www.lua.org/)
```

```sh
$ env RUST_LOG=debug RUST_BACKTRACE=1 linky --check  test.md 2&> linky_err.log
```

[linky_err.log](https://github.com/mattias-p/linky/files/1728966/linky_err.log)

**Comment by mattias-p** [comment]
Thank you very much for the bug report! I'll look into it.

**Comment by mattias-p** [comment]
A fix for this has been merged into the master branch. I ended up implementing reasonable support for character encodings.
